const Cart = require('../models/Cart');
const Product = require('../models/Product');

// @desc    Get user cart
// @route   GET /api/cart
// @access  Private
const getCart = async (req, res) => {
    try {
        let cart = await Cart.findOne({ user: req.user._id });

        if (!cart) {
            cart = await Cart.create({ user: req.user._id, items: [] });
        }

        // We need to fetch product details manually since we used Number for product IDRef (which is not standard MongoDB ObjectIDref)
        // Ideally, we'd use populate, but since Product.id is a custom Number field, populate might require 'localField' and 'foreignField' in schema.
        // Let's try to populate properly if we adjust Schema, but for now, let's just manual aggregate or use virtuals if standard populate fails.
        // Actually, let's adjust the Model to use virtuals or just simple aggregation. 
        // For simplicity and matching the existing Product model:

        // Wait, Mongoose populate works with refs even if they are not ObjectIds if configured correctly, but 'ref' usually expects _id. 
        // Since Product schema uses `id: Number` as a custom ID but still has an `_id: ObjectId` auto-generated by Mongo, 
        // we should check if we stored `product` as the custom `id` (Number) or the `_id` (ObjectId).
        // The Product model provided: 
        // id: { type: Number, required: true, unique: true }
        // 
        // If we store `product: 1` (Number), populate won't simple work with standard `ref: 'Product'` which looks for `_id`.
        // So we will do a manual lookup for now to be safe and robust.

        const productIds = cart.items.map(item => item.product);
        const products = await Product.find({ id: { $in: productIds } });

        const cartItems = cart.items.map(item => {
            const product = products.find(p => p.id === item.product);
            return {
                ...item.toObject(),
                product: product || null
            };
        }).filter(item => item.product !== null); // Filter out items where product might have been deleted

        res.json(cartItems);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server Error' });
    }
};

// @desc    Add item to cart
// @route   POST /api/cart
// @access  Private
const addToCart = async (req, res) => {
    const { productId, quantity } = req.body;

    try {
        let cart = await Cart.findOne({ user: req.user._id });

        if (!cart) {
            cart = await Cart.create({ user: req.user._id, items: [] });
        }

        // Check if product exists
        const product = await Product.findOne({ id: productId });
        if (!product) {
            return res.status(404).json({ message: 'Product not found' });
        }

        const itemIndex = cart.items.findIndex(item => item.product === productId);

        if (itemIndex > -1) {
            // Product exists in cart, update quantity
            cart.items[itemIndex].quantity += quantity;
        } else {
            // Product does not exist in cart, add new item
            cart.items.push({ product: productId, quantity });
        }

        await cart.save();

        // Return updated cart with product details
        const productIds = cart.items.map(item => item.product);
        const products = await Product.find({ id: { $in: productIds } });

        const cartItems = cart.items.map(item => {
            const p = products.find(prod => prod.id === item.product);
            return {
                ...item.toObject(),
                product: p || null
            };
        });

        res.json(cartItems);

    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server Error' });
    }
};

// @desc    Update cart item quantity
// @route   PUT /api/cart/:productId
// @access  Private
const updateCartItem = async (req, res) => {
    const { quantity } = req.body;
    const productId = parseInt(req.params.productId);

    try {
        let cart = await Cart.findOne({ user: req.user._id });

        if (!cart) {
            return res.status(404).json({ message: 'Cart not found' });
        }

        const itemIndex = cart.items.findIndex(item => item.product === productId);

        if (itemIndex > -1) {
            if (quantity > 0) {
                cart.items[itemIndex].quantity = quantity;
            } else {
                // Remove item if quantity is 0 or less
                cart.items.splice(itemIndex, 1);
            }
            await cart.save();

            // Return updated cart
            const productIds = cart.items.map(item => item.product);
            const products = await Product.find({ id: { $in: productIds } });

            const cartItems = cart.items.map(item => {
                const p = products.find(prod => prod.id === item.product);
                return {
                    ...item.toObject(),
                    product: p || null
                };
            });
            res.json(cartItems);
        } else {
            res.status(404).json({ message: 'Item not found in cart' });
        }

    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server Error' });
    }
};

// @desc    Remove item from cart
// @route   DELETE /api/cart/:productId
// @access  Private
const removeFromCart = async (req, res) => {
    const productId = parseInt(req.params.productId);

    try {
        let cart = await Cart.findOne({ user: req.user._id });

        if (!cart) {
            return res.status(404).json({ message: 'Cart not found' });
        }

        cart.items = cart.items.filter(item => item.product !== productId);

        await cart.save();

        const productIds = cart.items.map(item => item.product);
        const products = await Product.find({ id: { $in: productIds } });

        const cartItems = cart.items.map(item => {
            const p = products.find(prod => prod.id === item.product);
            return {
                ...item.toObject(),
                product: p || null
            };
        });

        res.json(cartItems);

    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server Error' });
    }
};

// @desc    Clear cart
// @route   DELETE /api/cart
// @access  Private
const clearCart = async (req, res) => {
    try {
        let cart = await Cart.findOne({ user: req.user._id });

        if (cart) {
            cart.items = [];
            await cart.save();
        }

        res.json([]);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server Error' });
    }
};

module.exports = {
    getCart,
    addToCart,
    updateCartItem,
    removeFromCart,
    clearCart
};
